// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteSandboxIdData, DeleteSandboxIdErrors, DeleteSandboxIdResponses, GetConfigData, GetConfigResponses, GetHealthData, GetHealthResponses, GetIndexData, GetIndexResponses, GetSandboxData, GetSandboxIdData, GetSandboxIdErrors, GetSandboxIdResponses, GetSandboxResponses, PostSandboxData, PostSandboxErrors, PostSandboxResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Service Information
 */
export const getIndex = <ThrowOnError extends boolean = false>(options?: Options<GetIndexData, ThrowOnError>) => (options?.client ?? client).get<GetIndexResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get All Sandboxes
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options?: Options<GetSandboxData, ThrowOnError>) => (options?.client ?? client).get<GetSandboxResponses, unknown, ThrowOnError>({ url: '/sandbox', ...options });

/**
 * Create New Sandbox
 */
export const postSandbox = <ThrowOnError extends boolean = false>(options?: Options<PostSandboxData, ThrowOnError>) => (options?.client ?? client).post<PostSandboxResponses, PostSandboxErrors, ThrowOnError>({
    url: '/sandbox',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete Sandbox
 */
export const deleteSandboxId = <ThrowOnError extends boolean = false>(options: Options<DeleteSandboxIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteSandboxIdResponses, DeleteSandboxIdErrors, ThrowOnError>({ url: '/sandbox/{id}', ...options });

/**
 * Get Sandbox by ID
 */
export const getSandboxId = <ThrowOnError extends boolean = false>(options: Options<GetSandboxIdData, ThrowOnError>) => (options.client ?? client).get<GetSandboxIdResponses, GetSandboxIdErrors, ThrowOnError>({ url: '/sandbox/{id}', ...options });

/**
 * Get Configuration
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => (options?.client ?? client).get<GetConfigResponses, unknown, ThrowOnError>({ url: '/config', ...options });
