// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service details
     */
    200: {
        service: string;
        version: string;
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetSandboxData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sandbox';
};

export type GetSandboxResponses = {
    /**
     * Sandboxes retrieved successfully
     */
    200: {
        sandboxes: Array<{
            id: string;
            provider: 'cloudflare' | 'daytona' | 'vercel' | 'docker' | 'local';
            status: 'pending' | 'running' | 'stopped' | 'error';
            url?: string;
            createdAt: string;
            metadata?: {
                [key: string]: unknown;
            };
        }>;
    };
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type PostSandboxData = {
    body?: {
        url: string;
        type: 'GITHUB' | 'ARXIV';
        directory: string;
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        provider: 'cloudflare' | 'daytona' | 'vercel' | 'docker' | 'local';
    };
    path?: never;
    query?: never;
    url: '/sandbox';
};

export type PostSandboxErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostSandboxError = PostSandboxErrors[keyof PostSandboxErrors];

export type PostSandboxResponses = {
    /**
     * Sandbox created successfully
     */
    200: {
        success: boolean;
        message?: string;
        sandbox?: {
            id: string;
            provider: 'cloudflare' | 'daytona' | 'vercel' | 'docker' | 'local';
            status: 'pending' | 'running' | 'stopped' | 'error';
            url?: string;
            createdAt: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostSandboxResponse = PostSandboxResponses[keyof PostSandboxResponses];

export type DeleteSandboxIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sandbox/{id}';
};

export type DeleteSandboxIdErrors = {
    /**
     * Sandbox not found
     */
    404: {
        error: string;
    };
};

export type DeleteSandboxIdError = DeleteSandboxIdErrors[keyof DeleteSandboxIdErrors];

export type DeleteSandboxIdResponses = {
    /**
     * Sandbox deleted successfully
     */
    200: {
        success: boolean;
        message?: string;
        sandbox?: {
            id: string;
            provider: 'cloudflare' | 'daytona' | 'vercel' | 'docker' | 'local';
            status: 'pending' | 'running' | 'stopped' | 'error';
            url?: string;
            createdAt: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type DeleteSandboxIdResponse = DeleteSandboxIdResponses[keyof DeleteSandboxIdResponses];

export type GetSandboxIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sandbox/{id}';
};

export type GetSandboxIdErrors = {
    /**
     * Sandbox not found
     */
    404: {
        error: string;
    };
};

export type GetSandboxIdError = GetSandboxIdErrors[keyof GetSandboxIdErrors];

export type GetSandboxIdResponses = {
    /**
     * Sandbox retrieved successfully
     */
    200: {
        id: string;
        provider: 'cloudflare' | 'daytona' | 'vercel' | 'docker' | 'local';
        status: 'pending' | 'running' | 'stopped' | 'error';
        url?: string;
        createdAt: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
};

export type GetSandboxIdResponse = GetSandboxIdResponses[keyof GetSandboxIdResponses];
