import { useState, useMemo } from "react"
import { Sidebar } from "@/components/Sidebar"
import { ContextItem } from "@/components/ContextItem"
import { ChatInput } from "@/components/ChatInput"
import { TabBar } from "@/components/TabBar"
import { CommandDialog } from "@/components/CommandDialog"
import { Code } from "@/components/Code"
import type { Context } from "@/components/ContextItem"
import type { Tab } from "@/components/TabBar"
import type { MentionFile } from "@/components/FileMention"
import type { FileNode } from "@/components/FileTree"

// Sample file contents for demo
const sampleFileContents: Record<string, string> = {
  "/README.md": `# Next.js

The React Framework for the Web

## Getting Started

\`\`\`bash
npx create-next-app@latest
\`\`\`

## Features

- **Hybrid Rendering**: Static and Server rendering
- **TypeScript Support**: Built-in TypeScript support
- **File-based Routing**: Intuitive page-based routing
`,
  "/package.json": `{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}`,
  "/tsconfig.json": `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}`,
  "/src/index.ts": `export * from './app'
export * from './lib/utils'
export * from './lib/hooks'
`,
  "/src/app.tsx": `import React from 'react'
import { Navbar } from './components/Navbar'
import { Sidebar } from './components/Sidebar'

export default function App() {
  return (
    <div className="flex min-h-screen">
      <Sidebar />
      <main className="flex-1">
        <Navbar />
        <div className="p-8">
          <h1>Welcome to Next.js</h1>
        </div>
      </main>
    </div>
  )
}
`,
  "/src/app/layout.tsx": `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`,
  "/src/app/page.tsx": `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Hello, Next.js!</h1>
    </main>
  )
}
`,
  "/src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}
`,
  "/src/lib/utils.ts": `import { type ClassValue, clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('en-US').format(date)
}
`,
  "/src/lib/hooks.ts": `import { useState, useEffect, useCallback } from 'react'

export function useLocalStorage<T>(key: string, initialValue: T) {
  const [storedValue, setStoredValue] = useState<T>(initialValue)

  useEffect(() => {
    const item = window.localStorage.getItem(key)
    if (item) {
      setStoredValue(JSON.parse(item))
    }
  }, [key])

  const setValue = useCallback((value: T) => {
    setStoredValue(value)
    window.localStorage.setItem(key, JSON.stringify(value))
  }, [key])

  return [storedValue, setValue] as const
}
`,
  "/src/lib/api.ts": `const API_BASE = '/api'

export async function fetcher<T>(url: string): Promise<T> {
  const res = await fetch(\`\${API_BASE}\${url}\`)
  if (!res.ok) throw new Error('Failed to fetch')
  return res.json()
}

export async function post<T>(url: string, data: unknown): Promise<T> {
  const res = await fetch(\`\${API_BASE}\${url}\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  })
  if (!res.ok) throw new Error('Failed to post')
  return res.json()
}
`,
  "/src/components/ui/Button.tsx": `import { cn } from '@/lib/utils'
import { forwardRef } from 'react'

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'outline' | 'ghost'
  size?: 'sm' | 'md' | 'lg'
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = 'default', size = 'md', ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={cn(
          'inline-flex items-center justify-center rounded-md font-medium',
          variant === 'default' && 'bg-primary text-white',
          variant === 'outline' && 'border border-input',
          variant === 'ghost' && 'hover:bg-accent',
          size === 'sm' && 'h-8 px-3 text-sm',
          size === 'md' && 'h-10 px-4',
          size === 'lg' && 'h-12 px-6 text-lg',
          className
        )}
        {...props}
      />
    )
  }
)
`,
  "/src/components/ui/Input.tsx": `import { cn } from '@/lib/utils'
import { forwardRef } from 'react'

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}

export const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, type = 'text', ...props }, ref) => {
    return (
      <input
        type={type}
        ref={ref}
        className={cn(
          'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2',
          'text-sm placeholder:text-muted-foreground',
          'focus:outline-none focus:ring-2 focus:ring-ring',
          className
        )}
        {...props}
      />
    )
  }
)
`,
  "/src/components/Navbar.tsx": `export function Navbar() {
  return (
    <nav className="border-b">
      <div className="flex h-16 items-center px-4">
        <div className="font-bold">MyApp</div>
        <div className="ml-auto flex items-center space-x-4">
          <a href="/docs">Docs</a>
          <a href="/about">About</a>
        </div>
      </div>
    </nav>
  )
}
`,
  "/src/components/Sidebar.tsx": `export function Sidebar() {
  return (
    <aside className="w-64 border-r">
      <div className="p-4">
        <h2 className="font-semibold">Navigation</h2>
        <ul className="mt-4 space-y-2">
          <li><a href="/">Home</a></li>
          <li><a href="/dashboard">Dashboard</a></li>
          <li><a href="/settings">Settings</a></li>
        </ul>
      </div>
    </aside>
  )
}
`,
  "/src/config/config.ts": `export const config = {
  appName: 'Next.js App',
  apiUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000/api',
  isDev: process.env.NODE_ENV === 'development',
}
`,
  "/src/config/constants.ts": `export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  HOME: '/',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  SETTINGS: '/settings',
  LOGIN: '/login',
} as const

export const API_ENDPOINTS = {
  USERS: '/users',
  POSTS: '/posts',
  COMMENTS: '/comments',
} as const
`,
  "/supplementary/code/code.py": `import torch
import torch.nn as nn
import math

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads
        
        self.W_q = nn.Linear(d_model, d_model)
        self.W_k = nn.Linear(d_model, d_model)
        self.W_v = nn.Linear(d_model, d_model)
        self.W_o = nn.Linear(d_model, d_model)
        
    def forward(self, Q, K, V, mask=None):
        batch_size = Q.size(0)
        
        Q = self.W_q(Q).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        K = self.W_k(K).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        V = self.W_v(V).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.d_k)
        
        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)
        
        attention = torch.softmax(scores, dim=-1)
        output = torch.matmul(attention, V)
        
        output = output.transpose(1, 2).contiguous().view(batch_size, -1, self.d_model)
        return self.W_o(output)
`,
}

export default function Chat() {
  const [tabs, setTabs] = useState<Tab[]>([
    { id: "1", title: "new session", type: "chat" },
  ])
  const [activeTabId, setActiveTabId] = useState("1")
  const [commandOpen, setCommandOpen] = useState(false)

  const [contexts, setContexts] = useState<Context[]>([
    {
      id: "1",
      name: "github.com/vercel/next.js",
      files: [
        { name: "README.md", path: "/README.md" },
        { name: "package.json", path: "/package.json" },
        { name: "tsconfig.json", path: "/tsconfig.json" },
        { name: "index.ts", path: "/src/index.ts" },
        { name: "app.tsx", path: "/src/app.tsx" },
        { name: "layout.tsx", path: "/src/app/layout.tsx" },
        { name: "page.tsx", path: "/src/app/page.tsx" },
        { name: "globals.css", path: "/src/app/globals.css" },
        { name: "utils.ts", path: "/src/lib/utils.ts" },
        { name: "hooks.ts", path: "/src/lib/hooks.ts" },
        { name: "api.ts", path: "/src/lib/api.ts" },
        { name: "Button.tsx", path: "/src/components/ui/Button.tsx" },
        { name: "Input.tsx", path: "/src/components/ui/Input.tsx" },
        { name: "Modal.tsx", path: "/src/components/ui/Modal.tsx" },
        { name: "Navbar.tsx", path: "/src/components/Navbar.tsx" },
        { name: "Sidebar.tsx", path: "/src/components/Sidebar.tsx" },
        { name: "config.ts", path: "/src/config/config.ts" },
        { name: "constants.ts", path: "/src/config/constants.ts" },
      ],
    },
    {
      id: "2",
      name: "arxiv.org/abs/1706.03762",
      files: [
        { name: "attention-is-all-you-need.pdf", path: "/paper.pdf" },
        { name: "figure1.png", path: "/figures/figure1.png" },
        { name: "figure2.png", path: "/figures/figure2.png" },
        { name: "architecture.png", path: "/figures/diagrams/architecture.png" },
        { name: "supplementary.pdf", path: "/supplementary/supplementary.pdf" },
        { name: "code.py", path: "/supplementary/code/code.py" },
      ],
    },
  ])

  const handleAddContext = (url: string) => {
    console.log("Adding context:", url)
    // TODO: Fetch and parse the URL to get context data
    const newContext: Context = {
      id: Date.now().toString(),
      name: url,
      files: [],
    }
    setContexts([...contexts, newContext])
  }

  const handleDeleteContext = (id: string) => {
    setContexts(contexts.filter((context) => context.id !== id))
  }

  const handleSendMessage = (message: string, mentionedFiles?: MentionFile[]) => {
    console.log("Sending message:", message, "with files:", mentionedFiles)
    // TODO: Implement message sending logic
  }

  // Convert context files to MentionFile format
  const availableFiles = useMemo<MentionFile[]>(() => {
    return contexts.flatMap((context) =>
      context.files.map((file) => ({
        id: `${context.id}-${file.path}`,
        name: file.name,
        path: `${context.name}${file.path}`,
        type: "file" as const,
      }))
    )
  }, [contexts])

  const handleNewTab = () => {
    const newTab: Tab = {
      id: Date.now().toString(),
      title: "new session",
    }
    setTabs([...tabs, newTab])
    setActiveTabId(newTab.id)
  }

  const handleCloseTab = (id: string) => {
    const newTabs = tabs.filter((tab) => tab.id !== id)
    setTabs(newTabs)
    if (activeTabId === id && newTabs.length > 0) {
      const lastTab = newTabs[newTabs.length - 1]
      if (lastTab) {
        setActiveTabId(lastTab.id)
      }
    }
  }

  const handleFileClick = (file: FileNode) => {
    // Check if tab already exists for this file
    const existingTab = tabs.find((tab) => tab.id === file.path)
    if (existingTab) {
      setActiveTabId(existingTab.id)
      return
    }

    // Get file content from sample data
    const content = sampleFileContents[file.path] || `// content for ${file.path}`

    // Create new tab for the file
    const newTab: Tab = {
      id: file.path,
      title: file.name,
      type: "file",
      fileContent: content,
      filePath: file.path,
    }
    setTabs([...tabs, newTab])
    setActiveTabId(newTab.id)
  }

  // Get the active tab
  const activeTab = tabs.find((tab) => tab.id === activeTabId)

  return (
    <>
      <CommandDialog
        open={commandOpen}
        onOpenChange={setCommandOpen}
        onNewSession={handleNewTab}
        onAddContext={() => {
          // Focus on the sidebar add context input
          setCommandOpen(false)
        }}
        onClearChat={() => {
          console.log("Clear chat")
        }}
      />
      <div className="flex h-[calc(100vh-4rem)]">
      <Sidebar
        onAddContext={handleAddContext}
        contexts={contexts.map(c => ({ id: c.id, name: c.name }))}
      >
        {contexts.length === 0 ? (
          <div className="p-4 text-sm text-zinc-500">
            no context added yet. click "add context" to get started.
          </div>
        ) : (
          <div>
            {contexts.map((context) => (
              <ContextItem
                key={context.id}
                context={context}
                onDelete={handleDeleteContext}
                onFileClick={handleFileClick}
              />
            ))}
          </div>
        )}
      </Sidebar>

      <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
        {/* Tab Bar */}
        <TabBar
          tabs={tabs}
          activeTabId={activeTabId}
          onTabSelect={setActiveTabId}
          onTabClose={handleCloseTab}
          onNewTab={handleNewTab}
        />

        {/* Content area */}
        <div className="flex-1 relative">
          {/* Main content - scrollable */}
          <div className="h-full overflow-y-auto pb-32">
            {activeTab?.type === "file" && activeTab.fileContent ? (
              /* File viewer */
              <Code
                file={{
                  name: activeTab.title,
                  contents: activeTab.fileContent,
                }}
              />
            ) : (
              /* Chat messages area */
              <div className="p-8">
              </div>
            )}
          </div>

          {/* Floating chat input - always visible */}
          <ChatInput onSend={handleSendMessage} availableFiles={availableFiles} />
        </div>
      </div>
      </div>
    </>
  )
}
