// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetConfigProvidersData, GetConfigProvidersErrors, GetConfigProvidersResponses, GetFileListData, GetFileListErrors, GetFileListResponses, GetFileReadData, GetFileReadErrors, GetFileReadResponses, GetFileTreeData, GetFileTreeErrors, GetFileTreeResponses, GetHealthData, GetHealthResponses, GetIndexData, GetIndexResponses, GetInstanceAvailableData, GetInstanceAvailableResponses, GetInstanceCurrentData, GetInstanceCurrentResponses, GetSdkData, GetSdkResponses, GetSessionData, GetSessionErrors, GetSessionResponses, PostInstanceAddData, PostInstanceAddErrors, PostInstanceAddResponses, PostInstanceInitData, PostInstanceInitErrors, PostInstanceInitResponses, PostInstanceRemoveData, PostInstanceRemoveErrors, PostInstanceRemoveResponses, PostInstanceSwitchData, PostInstanceSwitchErrors, PostInstanceSwitchResponses, PostSessionData, PostSessionErrors, PostSessionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Service Information
 */
export const getIndex = <ThrowOnError extends boolean = false>(options?: Options<GetIndexData, ThrowOnError>) => (options?.client ?? client).get<GetIndexResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get All Sessions
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) => (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({ url: '/session', ...options });

/**
 * Create New Session
 */
export const postSession = <ThrowOnError extends boolean = false>(options?: Options<PostSessionData, ThrowOnError>) => (options?.client ?? client).post<PostSessionResponses, PostSessionErrors, ThrowOnError>({ url: '/session', ...options });

/**
 * Get Available SDKs
 */
export const getSdk = <ThrowOnError extends boolean = false>(options?: Options<GetSdkData, ThrowOnError>) => (options?.client ?? client).get<GetSdkResponses, unknown, ThrowOnError>({ url: '/sdk', ...options });

/**
 * Get Current Instance State
 */
export const getInstanceCurrent = <ThrowOnError extends boolean = false>(options?: Options<GetInstanceCurrentData, ThrowOnError>) => (options?.client ?? client).get<GetInstanceCurrentResponses, unknown, ThrowOnError>({ url: '/instance/current', ...options });

/**
 * Get All Available Instances
 */
export const getInstanceAvailable = <ThrowOnError extends boolean = false>(options?: Options<GetInstanceAvailableData, ThrowOnError>) => (options?.client ?? client).get<GetInstanceAvailableResponses, unknown, ThrowOnError>({ url: '/instance/available', ...options });

/**
 * Initialize Current Instance
 */
export const postInstanceInit = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceInitData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceInitResponses, PostInstanceInitErrors, ThrowOnError>({
    url: '/instance/init',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Add New Instance
 */
export const postInstanceAdd = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceAddData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceAddResponses, PostInstanceAddErrors, ThrowOnError>({
    url: '/instance/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Switch to Different Instance
 */
export const postInstanceSwitch = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceSwitchData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceSwitchResponses, PostInstanceSwitchErrors, ThrowOnError>({
    url: '/instance/switch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Remove Instance
 */
export const postInstanceRemove = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceRemoveData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceRemoveResponses, PostInstanceRemoveErrors, ThrowOnError>({
    url: '/instance/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get All Providers
 */
export const getConfigProviders = <ThrowOnError extends boolean = false>(options?: Options<GetConfigProvidersData, ThrowOnError>) => (options?.client ?? client).get<GetConfigProvidersResponses, GetConfigProvidersErrors, ThrowOnError>({ url: '/config/providers', ...options });

/**
 * List Files in Directory
 */
export const getFileList = <ThrowOnError extends boolean = false>(options?: Options<GetFileListData, ThrowOnError>) => (options?.client ?? client).get<GetFileListResponses, GetFileListErrors, ThrowOnError>({ url: '/file/list', ...options });

/**
 * Get File Tree Structure
 */
export const getFileTree = <ThrowOnError extends boolean = false>(options?: Options<GetFileTreeData, ThrowOnError>) => (options?.client ?? client).get<GetFileTreeResponses, GetFileTreeErrors, ThrowOnError>({ url: '/file/tree', ...options });

/**
 * Read File Content
 */
export const getFileRead = <ThrowOnError extends boolean = false>(options: Options<GetFileReadData, ThrowOnError>) => (options.client ?? client).get<GetFileReadResponses, GetFileReadErrors, ThrowOnError>({ url: '/file/read', ...options });
