// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service details
     */
    200: {
        service: string;
        version: string;
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type GetSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * Sessions retrieved successfully
     */
    200: {
        sessions: Array<{
            id: string;
            title?: string;
            createdAt?: string;
            updatedAt?: string;
            [key: string]: unknown | string | undefined;
        }>;
    };
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type PostSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type PostSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostSessionError = PostSessionErrors[keyof PostSessionErrors];

export type PostSessionResponses = {
    /**
     * Session created successfully
     */
    200: {
        id: string;
        title?: string;
        createdAt?: string;
        updatedAt?: string;
        [key: string]: unknown | string | undefined;
    };
};

export type PostSessionResponse = PostSessionResponses[keyof PostSessionResponses];

export type GetSdkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk';
};

export type GetSdkResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        description: string;
        version: string;
    }>;
};

export type GetSdkResponse = GetSdkResponses[keyof GetSdkResponses];

export type PostInstanceInitData = {
    body?: {
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        directory?: string;
    };
    path?: never;
    query?: never;
    url: '/instance/init';
};

export type PostInstanceInitErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceInitError = PostInstanceInitErrors[keyof PostInstanceInitErrors];

export type PostInstanceInitResponses = {
    /**
     * SDK initialized successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceInitResponse = PostInstanceInitResponses[keyof PostInstanceInitResponses];

export type GetInstanceStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/state';
};

export type GetInstanceStateResponses = {
    /**
     * Instance state retrieved successfully
     */
    200: {
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        directory: string;
    };
};

export type GetInstanceStateResponse = GetInstanceStateResponses[keyof GetInstanceStateResponses];

export type GetInstanceProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/projects';
};

export type GetInstanceProjectsResponses = {
    /**
     * Projects retrieved successfully
     */
    200: Array<{
        id: string;
        type: 'GITHUB' | 'ARXIV';
        url: string;
        directory: string;
        metadata?: {
            [key: string]: unknown;
        };
    }>;
};

export type GetInstanceProjectsResponse = GetInstanceProjectsResponses[keyof GetInstanceProjectsResponses];

export type PostInstanceProjectAddData = {
    body?: {
        url: string;
        directory?: string;
    };
    path?: never;
    query?: never;
    url: '/instance/project/add';
};

export type PostInstanceProjectAddErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceProjectAddError = PostInstanceProjectAddErrors[keyof PostInstanceProjectAddErrors];

export type PostInstanceProjectAddResponses = {
    /**
     * Project added successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceProjectAddResponse = PostInstanceProjectAddResponses[keyof PostInstanceProjectAddResponses];

export type PostInstanceProjectRemoveData = {
    body?: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/instance/project/remove';
};

export type PostInstanceProjectRemoveErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceProjectRemoveError = PostInstanceProjectRemoveErrors[keyof PostInstanceProjectRemoveErrors];

export type PostInstanceProjectRemoveResponses = {
    /**
     * Project removed successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceProjectRemoveResponse = PostInstanceProjectRemoveResponses[keyof PostInstanceProjectRemoveResponses];

export type GetConfigProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config/providers';
};

export type GetConfigProvidersErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetConfigProvidersError = GetConfigProvidersErrors[keyof GetConfigProvidersErrors];

export type GetConfigProvidersResponses = {
    /**
     * Providers retrieved successfully
     */
    200: {
        providers: Array<{
            id: string;
            name: string;
            models?: {
                [key: string]: unknown;
            };
            [key: string]: unknown | string | {
                [key: string]: unknown;
            } | undefined;
        }>;
        default: {
            [key: string]: string;
        };
    };
};

export type GetConfigProvidersResponse = GetConfigProvidersResponses[keyof GetConfigProvidersResponses];

export type GetFileListData = {
    body?: never;
    path?: never;
    query?: {
        path?: string;
    };
    url: '/file/list';
};

export type GetFileListErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileListError = GetFileListErrors[keyof GetFileListErrors];

export type GetFileListResponses = {
    /**
     * Files retrieved successfully
     */
    200: {
        files: Array<{
            name: string;
            path: string;
            type: 'file' | 'directory';
            size?: number;
            modifiedAt?: string;
        }>;
    };
};

export type GetFileListResponse = GetFileListResponses[keyof GetFileListResponses];

export type GetFileTreeData = {
    body?: never;
    path?: never;
    query?: {
        path?: string;
        maxDepth?: string;
    };
    url: '/file/tree';
};

export type GetFileTreeErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileTreeError = GetFileTreeErrors[keyof GetFileTreeErrors];

export type GetFileTreeResponses = {
    /**
     * File tree retrieved successfully
     */
    200: {
        tree: {
            name: string;
            path: string;
            type: 'file' | 'directory';
            children?: Array<{
                name: string;
                path: string;
                type: 'file' | 'directory';
                size?: number;
                modifiedAt?: string;
            }>;
            size?: number;
            modifiedAt?: string;
        };
    };
};

export type GetFileTreeResponse = GetFileTreeResponses[keyof GetFileTreeResponses];

export type GetFileReadData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/file/read';
};

export type GetFileReadErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileReadError = GetFileReadErrors[keyof GetFileReadErrors];

export type GetFileReadResponses = {
    /**
     * File content retrieved successfully
     */
    200: {
        content: string;
    };
};

export type GetFileReadResponse = GetFileReadResponses[keyof GetFileReadResponses];
