// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TimeCreated = {
    created: number;
};

export type FileDiff = {
    file: string;
    before: string;
    after: string;
    additions: number;
    deletions: number;
};

export type Model = {
    providerID: string;
    modelID: string;
};

export type UserMessage = {
    id: string;
    sessionID: string;
    role: 'user';
    time: TimeCreated;
    summary?: {
        title?: string;
        body?: string;
        diffs: Array<FileDiff>;
    };
    agent: string;
    model: Model;
    system?: string;
    tools?: {
        [key: string]: boolean;
    };
};

export type TimeCompleted = {
    created: number;
    completed?: number;
};

export type ProviderAuthError = {
    name: 'ProviderAuthError';
    data: {
        providerID: string;
        message: string;
    };
};

export type UnknownError = {
    name: 'UnknownError';
    data: {
        message: string;
    };
};

export type MessageOutputLengthError = {
    name: 'MessageOutputLengthError';
    data: {
        [key: string]: unknown;
    };
};

export type MessageAbortedError = {
    name: 'MessageAbortedError';
    data: {
        message: string;
    };
};

export type ApiError = {
    name: 'APIError';
    data: {
        message: string;
        statusCode?: number;
        isRetryable: boolean;
        responseHeaders?: {
            [key: string]: string;
        };
        responseBody?: string;
    };
};

export type AssistantMessage = {
    id: string;
    sessionID: string;
    role: 'assistant';
    time: TimeCompleted;
    error?: ProviderAuthError | UnknownError | MessageOutputLengthError | MessageAbortedError | ApiError;
    parentID: string;
    modelID: string;
    providerID: string;
    mode: string;
    path: {
        cwd: string;
        root: string;
    };
    summary?: boolean;
    cost: number;
    tokens: {
        input: number;
        output: number;
        reasoning: number;
        cache: {
            read: number;
            write: number;
        };
    };
    finish?: string;
};

export type TextPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'text';
    text: string;
    synthetic?: boolean;
    ignored?: boolean;
    time?: {
        start: number;
        end?: number;
    };
    metadata?: {
        [key: string]: unknown;
    };
};

export type ReasoningPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'reasoning';
    text: string;
    metadata?: {
        [key: string]: unknown;
    };
    time: {
        start: number;
        end?: number;
    };
};

export type FilePartSourceText = {
    value: string;
    start: number;
    end: number;
};

export type FileSource = {
    type: 'file';
    text: FilePartSourceText;
    path: string;
};

export type Range = {
    start: {
        line: number;
        character: number;
    };
    end: {
        line: number;
        character: number;
    };
};

export type SymbolSource = {
    type: 'symbol';
    text: FilePartSourceText;
    path: string;
    range: Range;
    name: string;
    kind: number;
};

export type FilePart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'file';
    mime: string;
    filename?: string;
    url: string;
    source?: FileSource | SymbolSource;
};

export type ToolStatePending = {
    status: 'pending';
    input: {
        [key: string]: unknown;
    };
    raw: string;
};

export type ToolStateRunning = {
    status: 'running';
    input: {
        [key: string]: unknown;
    };
    title?: string;
    metadata?: {
        [key: string]: unknown;
    };
    time: {
        start: number;
    };
};

export type ToolStateCompleted = {
    status: 'completed';
    input: {
        [key: string]: unknown;
    };
    output: string;
    title: string;
    metadata: {
        [key: string]: unknown;
    };
    time: {
        start: number;
        end: number;
        compacted?: number;
    };
    attachments?: Array<FilePart>;
};

export type ToolStateError = {
    status: 'error';
    input: {
        [key: string]: unknown;
    };
    error: string;
    metadata?: {
        [key: string]: unknown;
    };
    time: {
        start: number;
        end: number;
    };
};

export type ToolPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'tool';
    callID: string;
    tool: string;
    state: ToolStatePending | ToolStateRunning | ToolStateCompleted | ToolStateError;
    metadata?: {
        [key: string]: unknown;
    };
};

export type StepStartPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'step-start';
    snapshot?: string;
};

export type StepFinishPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'step-finish';
    reason: string;
    snapshot?: string;
    cost: number;
    tokens: {
        input: number;
        output: number;
        reasoning: number;
        cache: {
            read: number;
            write: number;
        };
    };
};

export type SnapshotPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'snapshot';
    snapshot: string;
};

export type PatchPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'patch';
    hash: string;
    files: Array<string>;
};

export type AgentPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'agent';
    name: string;
    source?: {
        value: string;
        start: number;
        end: number;
    };
};

export type SubtaskPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'subtask';
    prompt: string;
    description: string;
    agent: string;
};

export type RetryPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'retry';
    attempt: number;
    error: ApiError;
    time: {
        created: number;
    };
};

export type CompactionPart = {
    id: string;
    sessionID: string;
    messageID: string;
    type: 'compaction';
};

export type MessageWithParts = {
    info: UserMessage | AssistantMessage;
    parts: Array<TextPart | ReasoningPart | FilePart | ToolPart | StepStartPart | StepFinishPart | SnapshotPart | PatchPart | AgentPart | SubtaskPart | RetryPart | CompactionPart>;
};

export type SseEnvelope = {
    /**
     * Envelope version
     */
    v: number;
    /**
     * Event type
     */
    type: string;
    /**
     * Event data/properties
     */
    data: unknown;
    /**
     * Timestamp
     */
    ts: number;
};

export type TextPartInput = {
    type: 'text';
    text: string;
};

export type FilePartInput = {
    type: 'file';
    path: string;
};

export type AgentPartInput = {
    type: 'agent';
    name: string;
};

export type SubtaskPartInput = {
    type: 'subtask';
    prompt: string;
    description: string;
    agent: string;
};

export type PromptRequest = {
    messageID?: string;
    model?: Model;
    agent?: string;
    noReply?: boolean;
    system?: string;
    tools?: {
        [key: string]: boolean;
    };
    parts: Array<TextPartInput | FilePartInput | AgentPartInput | SubtaskPartInput>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service details
     */
    200: {
        service: string;
        version: string;
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type GetSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * Sessions retrieved successfully
     */
    200: {
        sessions: Array<{
            id: string;
            title?: string;
            createdAt?: string;
            updatedAt?: string;
            [key: string]: unknown | string | undefined;
        }>;
    };
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type PostSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type PostSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostSessionError = PostSessionErrors[keyof PostSessionErrors];

export type PostSessionResponses = {
    /**
     * Session created successfully
     */
    200: {
        id: string;
        title?: string;
        createdAt?: string;
        updatedAt?: string;
        [key: string]: unknown | string | undefined;
    };
};

export type PostSessionResponse = PostSessionResponses[keyof PostSessionResponses];

export type GetSessionIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/session/{id}/messages';
};

export type GetSessionIdMessagesErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
    /**
     * Session not found
     */
    404: {
        error: string;
    };
};

export type GetSessionIdMessagesError = GetSessionIdMessagesErrors[keyof GetSessionIdMessagesErrors];

export type GetSessionIdMessagesResponses = {
    /**
     * Messages retrieved successfully
     */
    200: Array<MessageWithParts>;
};

export type GetSessionIdMessagesResponse = GetSessionIdMessagesResponses[keyof GetSessionIdMessagesResponses];

export type PostSessionIdMessageData = {
    body?: PromptRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/session/{id}/message';
};

export type PostSessionIdMessageErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
    /**
     * Session not found
     */
    404: {
        error: string;
    };
};

export type PostSessionIdMessageError = PostSessionIdMessageErrors[keyof PostSessionIdMessageErrors];

export type PostSessionIdMessageResponses = {
    /**
     * Server-sent events stream with OpenCode events
     */
    200: SseEnvelope;
};

export type PostSessionIdMessageResponse = PostSessionIdMessageResponses[keyof PostSessionIdMessageResponses];

export type GetSdkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk';
};

export type GetSdkResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        description: string;
        version: string;
    }>;
};

export type GetSdkResponse = GetSdkResponses[keyof GetSdkResponses];

export type PostInstanceInitData = {
    body?: {
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        directory?: string;
    };
    path?: never;
    query?: never;
    url: '/instance/init';
};

export type PostInstanceInitErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceInitError = PostInstanceInitErrors[keyof PostInstanceInitErrors];

export type PostInstanceInitResponses = {
    /**
     * SDK initialized successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceInitResponse = PostInstanceInitResponses[keyof PostInstanceInitResponses];

export type GetInstanceStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/state';
};

export type GetInstanceStateResponses = {
    /**
     * Instance state retrieved successfully
     */
    200: {
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        directory: string;
    };
};

export type GetInstanceStateResponse = GetInstanceStateResponses[keyof GetInstanceStateResponses];

export type GetInstanceProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/projects';
};

export type GetInstanceProjectsResponses = {
    /**
     * Projects retrieved successfully
     */
    200: Array<{
        id: string;
        type: 'GITHUB' | 'ARXIV';
        url: string;
        directory: string;
        metadata?: {
            [key: string]: unknown;
        };
    }>;
};

export type GetInstanceProjectsResponse = GetInstanceProjectsResponses[keyof GetInstanceProjectsResponses];

export type PostInstanceProjectAddData = {
    body?: {
        url: string;
        directory?: string;
    };
    path?: never;
    query?: never;
    url: '/instance/project/add';
};

export type PostInstanceProjectAddErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceProjectAddError = PostInstanceProjectAddErrors[keyof PostInstanceProjectAddErrors];

export type PostInstanceProjectAddResponses = {
    /**
     * Project added successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceProjectAddResponse = PostInstanceProjectAddResponses[keyof PostInstanceProjectAddResponses];

export type PostInstanceProjectRemoveData = {
    body?: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/instance/project/remove';
};

export type PostInstanceProjectRemoveErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceProjectRemoveError = PostInstanceProjectRemoveErrors[keyof PostInstanceProjectRemoveErrors];

export type PostInstanceProjectRemoveResponses = {
    /**
     * Project removed successfully
     */
    200: {
        success: boolean;
        message?: string;
        project?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceProjectRemoveResponse = PostInstanceProjectRemoveResponses[keyof PostInstanceProjectRemoveResponses];

export type GetConfigProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config/providers';
};

export type GetConfigProvidersErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetConfigProvidersError = GetConfigProvidersErrors[keyof GetConfigProvidersErrors];

export type GetConfigProvidersResponses = {
    /**
     * Providers retrieved successfully
     */
    200: {
        providers: Array<{
            id: string;
            name: string;
            models?: {
                [key: string]: unknown;
            };
            [key: string]: unknown | string | {
                [key: string]: unknown;
            } | undefined;
        }>;
        default: {
            [key: string]: string;
        };
    };
};

export type GetConfigProvidersResponse = GetConfigProvidersResponses[keyof GetConfigProvidersResponses];

export type GetFileListData = {
    body?: never;
    path?: never;
    query?: {
        path?: string;
    };
    url: '/file/list';
};

export type GetFileListErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileListError = GetFileListErrors[keyof GetFileListErrors];

export type GetFileListResponses = {
    /**
     * Files retrieved successfully
     */
    200: {
        files: Array<{
            name: string;
            path: string;
            type: 'file' | 'directory';
            size?: number;
            modifiedAt?: string;
        }>;
    };
};

export type GetFileListResponse = GetFileListResponses[keyof GetFileListResponses];

export type GetFileTreeData = {
    body?: never;
    path?: never;
    query?: {
        path?: string;
        maxDepth?: string;
    };
    url: '/file/tree';
};

export type GetFileTreeErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileTreeError = GetFileTreeErrors[keyof GetFileTreeErrors];

export type GetFileTreeResponses = {
    /**
     * File tree retrieved successfully
     */
    200: {
        tree: {
            name: string;
            path: string;
            type: 'file' | 'directory';
            children?: Array<{
                name: string;
                path: string;
                type: 'file' | 'directory';
                size?: number;
                modifiedAt?: string;
            }>;
            size?: number;
            modifiedAt?: string;
        };
    };
};

export type GetFileTreeResponse = GetFileTreeResponses[keyof GetFileTreeResponses];

export type GetFileReadData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/file/read';
};

export type GetFileReadErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetFileReadError = GetFileReadErrors[keyof GetFileReadErrors];

export type GetFileReadResponses = {
    /**
     * File content retrieved successfully
     */
    200: {
        content: string;
    };
};

export type GetFileReadResponse = GetFileReadResponses[keyof GetFileReadResponses];
