// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetConfigProvidersData, GetConfigProvidersErrors, GetConfigProvidersResponses, GetFileListData, GetFileListErrors, GetFileListResponses, GetFileReadData, GetFileReadErrors, GetFileReadResponses, GetFileTreeData, GetFileTreeErrors, GetFileTreeResponses, GetHealthData, GetHealthResponses, GetIndexData, GetIndexResponses, GetInstanceProjectsData, GetInstanceProjectsResponses, GetInstanceStateData, GetInstanceStateResponses, GetSdkData, GetSdkResponses, GetSessionData, GetSessionErrors, GetSessionIdMessagesData, GetSessionIdMessagesErrors, GetSessionIdMessagesResponses, GetSessionResponses, PostInstanceInitData, PostInstanceInitErrors, PostInstanceInitResponses, PostInstanceProjectAddData, PostInstanceProjectAddErrors, PostInstanceProjectAddResponses, PostInstanceProjectRemoveData, PostInstanceProjectRemoveErrors, PostInstanceProjectRemoveResponses, PostSessionData, PostSessionErrors, PostSessionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Service Information
 */
export const getIndex = <ThrowOnError extends boolean = false>(options?: Options<GetIndexData, ThrowOnError>) => (options?.client ?? client).get<GetIndexResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get All Sessions
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) => (options?.client ?? client).get<GetSessionResponses, GetSessionErrors, ThrowOnError>({ url: '/session', ...options });

/**
 * Create New Session
 */
export const postSession = <ThrowOnError extends boolean = false>(options?: Options<PostSessionData, ThrowOnError>) => (options?.client ?? client).post<PostSessionResponses, PostSessionErrors, ThrowOnError>({ url: '/session', ...options });

/**
 * Get Messages for Session
 */
export const getSessionIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetSessionIdMessagesData, ThrowOnError>) => (options.client ?? client).get<GetSessionIdMessagesResponses, GetSessionIdMessagesErrors, ThrowOnError>({ url: '/session/{id}/messages', ...options });

/**
 * Get Available SDKs
 */
export const getSdk = <ThrowOnError extends boolean = false>(options?: Options<GetSdkData, ThrowOnError>) => (options?.client ?? client).get<GetSdkResponses, unknown, ThrowOnError>({ url: '/sdk', ...options });

/**
 * Initialize SDK
 */
export const postInstanceInit = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceInitData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceInitResponses, PostInstanceInitErrors, ThrowOnError>({
    url: '/instance/init',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get Instance State
 */
export const getInstanceState = <ThrowOnError extends boolean = false>(options?: Options<GetInstanceStateData, ThrowOnError>) => (options?.client ?? client).get<GetInstanceStateResponses, unknown, ThrowOnError>({ url: '/instance/state', ...options });

/**
 * Get All Projects
 */
export const getInstanceProjects = <ThrowOnError extends boolean = false>(options?: Options<GetInstanceProjectsData, ThrowOnError>) => (options?.client ?? client).get<GetInstanceProjectsResponses, unknown, ThrowOnError>({ url: '/instance/projects', ...options });

/**
 * Add New Project
 */
export const postInstanceProjectAdd = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceProjectAddData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceProjectAddResponses, PostInstanceProjectAddErrors, ThrowOnError>({
    url: '/instance/project/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Remove Project
 */
export const postInstanceProjectRemove = <ThrowOnError extends boolean = false>(options?: Options<PostInstanceProjectRemoveData, ThrowOnError>) => (options?.client ?? client).post<PostInstanceProjectRemoveResponses, PostInstanceProjectRemoveErrors, ThrowOnError>({
    url: '/instance/project/remove',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get All Providers
 */
export const getConfigProviders = <ThrowOnError extends boolean = false>(options?: Options<GetConfigProvidersData, ThrowOnError>) => (options?.client ?? client).get<GetConfigProvidersResponses, GetConfigProvidersErrors, ThrowOnError>({ url: '/config/providers', ...options });

/**
 * List Files in Directory
 */
export const getFileList = <ThrowOnError extends boolean = false>(options?: Options<GetFileListData, ThrowOnError>) => (options?.client ?? client).get<GetFileListResponses, GetFileListErrors, ThrowOnError>({ url: '/file/list', ...options });

/**
 * Get File Tree Structure
 */
export const getFileTree = <ThrowOnError extends boolean = false>(options?: Options<GetFileTreeData, ThrowOnError>) => (options?.client ?? client).get<GetFileTreeResponses, GetFileTreeErrors, ThrowOnError>({ url: '/file/tree', ...options });

/**
 * Read File Content
 */
export const getFileRead = <ThrowOnError extends boolean = false>(options: Options<GetFileReadData, ThrowOnError>) => (options.client ?? client).get<GetFileReadResponses, GetFileReadErrors, ThrowOnError>({ url: '/file/read', ...options });
