// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
        timestamp: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetIndexData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetIndexResponses = {
    /**
     * Service details
     */
    200: {
        service: string;
        version: string;
    };
};

export type GetIndexResponse = GetIndexResponses[keyof GetIndexResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type GetSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * Sessions retrieved successfully
     */
    200: {
        sessions: Array<{
            id: string;
            title?: string;
            createdAt?: string;
            updatedAt?: string;
            [key: string]: unknown | string | undefined;
        }>;
    };
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type PostSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type PostSessionErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostSessionError = PostSessionErrors[keyof PostSessionErrors];

export type PostSessionResponses = {
    /**
     * Session created successfully
     */
    200: {
        id: string;
        title?: string;
        createdAt?: string;
        updatedAt?: string;
        [key: string]: unknown | string | undefined;
    };
};

export type PostSessionResponse = PostSessionResponses[keyof PostSessionResponses];

export type GetSdkData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk';
};

export type GetSdkResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        description: string;
        version: string;
    }>;
};

export type GetSdkResponse = GetSdkResponses[keyof GetSdkResponses];

export type GetInstanceCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/current';
};

export type GetInstanceCurrentResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        type: 'GITHUB' | 'ARXIV';
        url: string;
        directory: string;
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        metadata?: {
            [key: string]: unknown;
        };
    };
};

export type GetInstanceCurrentResponse = GetInstanceCurrentResponses[keyof GetInstanceCurrentResponses];

export type GetInstanceAvailableData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/instance/available';
};

export type GetInstanceAvailableResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        type: 'GITHUB' | 'ARXIV';
        url: string;
        directory: string;
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
        metadata?: {
            [key: string]: unknown;
        };
    }>;
};

export type GetInstanceAvailableResponse = GetInstanceAvailableResponses[keyof GetInstanceAvailableResponses];

export type PostInstanceInitData = {
    body?: {
        url: string;
        type: 'GITHUB' | 'ARXIV';
        directory: string;
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
    };
    path?: never;
    query?: never;
    url: '/instance/init';
};

export type PostInstanceInitErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceInitError = PostInstanceInitErrors[keyof PostInstanceInitErrors];

export type PostInstanceInitResponses = {
    /**
     * Instance initialized successfully
     */
    200: {
        success: boolean;
        message?: string;
        directory?: string;
        instance?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            sdkType: 'OPENCODE' | 'CLAUDE_CODE';
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceInitResponse = PostInstanceInitResponses[keyof PostInstanceInitResponses];

export type PostInstanceAddData = {
    body?: {
        url: string;
        type: 'GITHUB' | 'ARXIV';
        directory: string;
        sdkType: 'OPENCODE' | 'CLAUDE_CODE';
    };
    path?: never;
    query?: never;
    url: '/instance/add';
};

export type PostInstanceAddErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceAddError = PostInstanceAddErrors[keyof PostInstanceAddErrors];

export type PostInstanceAddResponses = {
    /**
     * Instance added successfully
     */
    200: {
        success: boolean;
        message?: string;
        directory?: string;
        instance?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            sdkType: 'OPENCODE' | 'CLAUDE_CODE';
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceAddResponse = PostInstanceAddResponses[keyof PostInstanceAddResponses];

export type PostInstanceSwitchData = {
    body?: {
        instanceId: string;
    };
    path?: never;
    query?: never;
    url: '/instance/switch';
};

export type PostInstanceSwitchErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceSwitchError = PostInstanceSwitchErrors[keyof PostInstanceSwitchErrors];

export type PostInstanceSwitchResponses = {
    /**
     * Instance switched successfully
     */
    200: {
        success: boolean;
        message?: string;
        directory?: string;
        instance?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            sdkType: 'OPENCODE' | 'CLAUDE_CODE';
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceSwitchResponse = PostInstanceSwitchResponses[keyof PostInstanceSwitchResponses];

export type PostInstanceRemoveData = {
    body?: {
        instanceId: string;
    };
    path?: never;
    query?: never;
    url: '/instance/remove';
};

export type PostInstanceRemoveErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type PostInstanceRemoveError = PostInstanceRemoveErrors[keyof PostInstanceRemoveErrors];

export type PostInstanceRemoveResponses = {
    /**
     * Instance removed successfully
     */
    200: {
        success: boolean;
        message?: string;
        directory?: string;
        instance?: {
            id: string;
            type: 'GITHUB' | 'ARXIV';
            url: string;
            directory: string;
            sdkType: 'OPENCODE' | 'CLAUDE_CODE';
            metadata?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostInstanceRemoveResponse = PostInstanceRemoveResponses[keyof PostInstanceRemoveResponses];

export type GetConfigProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config/providers';
};

export type GetConfigProvidersErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
    };
};

export type GetConfigProvidersError = GetConfigProvidersErrors[keyof GetConfigProvidersErrors];

export type GetConfigProvidersResponses = {
    /**
     * Providers retrieved successfully
     */
    200: {
        providers: Array<{
            id: string;
            name: string;
            models?: {
                [key: string]: unknown;
            };
            [key: string]: unknown | string | {
                [key: string]: unknown;
            } | undefined;
        }>;
        default: {
            [key: string]: string;
        };
    };
};

export type GetConfigProvidersResponse = GetConfigProvidersResponses[keyof GetConfigProvidersResponses];
